Fix building of nwb-schema documentation
This commit fixes the following error by addressing a regression introduced
in cddf2b3 (Merge pull request #26 from NeurodataWithoutBorders/fix/postifix):

  Traceback (most recent call last):
    File "/home/jcfr/.virtualenvs/nwb/bin/nwb_generate_format_docs", line 11, in <module>
      load_entry_point('nwb-docutils', 'console_scripts', 'nwb_generate_format_docs')()
    File "/home/jcfr/Projects/nwb-docutils/nwb_docutils/generate_format_docs.py", line 542, in main
      print_status=True)
    File "/home/jcfr/Projects/nwb-docutils/nwb_docutils/generate_format_docs.py", line 390, in render_data_type_section
      parent='' if rt != 'NWBFile' else '/')
    File "/home/jcfr/Projects/nwb-docutils/nwb_docutils/doctools/renderrst.py", line 788, in render_group_spec
      rst_format='**')
  TypeError: clean_schema_doc_string() got an unexpected keyword argument 'add_postifix'
  Makefile:175: recipe for target 'apidoc' failed
  make: *** [apidoc] Error 1